#!/usr/bin/env python3
"""Pack ui/ + nv_webui.py into netquality.py for signed single-file updates.

Writes a base64 zip between marker comments in netquality.py. At runtime
`_ensure_nv_webui()` extracts it beside the script (or into the config dir)
so `import nv_webui` works after an in-app Update that only replaces
netquality.py.

Usage:
  python tools/embed_ui.py           # pack into netquality.py
  python tools/embed_ui.py --check   # verify markers + round-trip
"""
from __future__ import annotations

import argparse
import base64
import io
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NQ = os.path.join(ROOT, "netquality.py")
UI = os.path.join(ROOT, "ui")
WEBUI = os.path.join(ROOT, "nv_webui.py")

BEGIN = "# --- BEGIN NV_WEBUI_ZIP ---"
END = "# --- END NV_WEBUI_ZIP ---"
ASSIGN = "_NV_WEBUI_ZIP_B64 = "


def collect_zip_bytes():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(WEBUI, arcname="nv_webui.py")
        for dirpath, _dirs, files in os.walk(UI):
            for name in files:
                if name.startswith(".") or name == "_bundle.py":
                    continue
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
                zf.write(full, arcname=rel)
    return buf.getvalue()


def render_block(b64: str) -> str:
    # Split into ~76-char lines for readable diffs / editors
    lines = [b64[i:i + 76] for i in range(0, len(b64), 76)]
    body = "\n".join(f"    {ln!r}" for ln in lines)
    return (
        f"{BEGIN}\n"
        f"# Auto-generated by tools/embed_ui.py — do not edit by hand.\n"
        f"{ASSIGN}(\n{body}\n)\n"
        f"{END}\n"
    )


def inject(src: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
        re.S,
    )
    if pattern.search(src):
        return pattern.sub(block, src, count=1)
    # Place after __version__ / UPDATE_URL preamble — before first big section.
    anchor = "\n# ---------------------------------------------------------------------------\n"
    idx = src.find(anchor)
    if idx < 0:
        return src + "\n" + block
    return src[:idx] + "\n" + block + "\n" + src[idx:]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()

    raw = collect_zip_bytes()
    b64 = base64.b64encode(raw).decode("ascii")
    block = render_block(b64)
    print(f"zip {len(raw)} bytes → {len(b64)} base64 chars")

    with open(NQ, "r", encoding="utf-8") as fh:
        src = fh.read()
    new = inject(src, block)
    if args.check:
        if BEGIN not in new or END not in new:
            print("FAIL: markers missing after inject", file=sys.stderr)
            return 1
        # Round-trip decode
        m = re.search(
            re.escape(ASSIGN) + r"\((.*?)\)\n" + re.escape(END),
            new,
            re.S,
        )
        if not m:
            print("FAIL: assignment not found", file=sys.stderr)
            return 1
        joined = "".join(re.findall(r"'([^']*)'", m.group(1)))
        decoded = base64.b64decode(joined)
        with zipfile.ZipFile(io.BytesIO(decoded)) as zf:
            names = zf.namelist()
        assert "nv_webui.py" in names
        assert any(n.startswith("ui/") for n in names)
        print("check ok:", len(names), "entries")
        return 0

    if new == src:
        print("netquality.py unchanged")
        return 0
    with open(NQ, "w", encoding="utf-8") as fh:
        fh.write(new)
    print("updated", NQ)
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
