#!/usr/bin/env python3
"""Pack ui/ into a Python dict literal for single-file embedding (optional).

Usage:
  python tools/embed_ui.py            # print dict size summary
  python tools/embed_ui.py --write    # write ui/_bundle.py for inspection

Signed updates still ship netquality.py; keep ui/ + nv_webui.py beside it in
git checkouts. A future release packer can inline this bundle into
netquality.py without changing the HTTP API.
"""
import argparse
import base64
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UI = os.path.join(ROOT, "ui")


def collect():
    out = {}
    for dirpath, _dirs, files in os.walk(UI):
        for name in files:
            if name.startswith(".") or name == "_bundle.py":
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, UI).replace(os.sep, "/")
            with open(full, "rb") as fh:
                out[rel] = base64.b64encode(fh.read()).decode("ascii")
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--write", action="store_true")
    args = p.parse_args()
    data = collect()
    total = sum(len(v) for v in data.values())
    print(f"{len(data)} files, {total} base64 chars")
    if args.write:
        path = os.path.join(UI, "_bundle.py")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("# Auto-generated by tools/embed_ui.py — do not edit.\n")
            fh.write("UI_BUNDLE = {\n")
            for k in sorted(data):
                fh.write(f"    {k!r}: {data[k]!r},\n")
            fh.write("}\n")
        print("wrote", path)


if __name__ == "__main__":
    sys.exit(main() or 0)
